server:
  port: 8000
spring:
  application:
    name: platform-client-user
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
logging:
  config: classpath:logback.xml
  level:
    com:
      platform:
        client:
          user:
            interfaces:
              UserRemoteClient: debug