server:
  port: 8000
spring:
  application:
    name: platform-client-user
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
logging:
  config: classpath:logback.xml
  level:
    com:
      platform:
        client:
          user:
            interfaces:
              UserRemoteClient: debug
feign:
  hystrix:
    enabled: true
