server:
  port: 8081

spring:
  application:
    name: platform-proxy

zuul:
  routes:
    platform-client:
      path: /client/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
