server:
  port: 8081

spring:
  application:
    name: platform-proxy
  resources:
    static-locations: classpath:/static/, classpath:/templates/
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/platform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

zuul:
  routes:
    platform-client:
      path: /client/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
