server:
  port: 8081

spring:
  application:
    name: platform-proxy
  resources:
    static-locations: classpath:/static/, classpath:/templates/
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/platform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

zuul:
  routes:
    platform-client:
      path: /client/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/


# cas
cas:
  server:
    prefix: http://127.0.0.1:8080/cas
    login: ${cas.server.prefix}/login
    logout: ${cas.server.prefix}/logout
  client:
    prefix: http://127.0.0.1:${server.port}
    login: ${cas.client.prefix}/login/cas
    logout:
      relative: /logout/cas
      absolute: ${cas.client.prefix}${cas.client.logout.relative}


# 初始化超级管理员账户、角色、权限
my:
  system:
    init: false
    admin:
      username: admin
      password: 123456
      disable: false
    roles[0]:
      role-name: 超级管理员
    authorities[0]:
      authority-name: 管理员管理
      authority-url: /admin/**
    authorities[1]:
      authority-name: 角色管理
      authority-url: /role/**
    authorities[2]:
      authority-name: 权限管理
      authority-url: /authority/**
    authorities[3]:
      authority-name: 用户授权
      authority-url: /adminrole/grant
    authorities[4]:
      authority-name: 角色授权
      authority-url: /roleauthority/grant
