server:
  port: 8082

cas:
  server:
    prefix: http://127.0.0.1:8080/cas
    login: ${cas.service.prefix}/login
    logout: ${cas.service.prefix}/logout
  client:
    prefix: http://127.0.0.1:${service.port}
    login: ${cas.client.prefix}/login/cas
    logout:
      relative: /logout/cas
      url: ${cas.client.prefix}${cas.client.logout.relative}
  user:
    inmemory: admin
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/platform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
