server:
  port: 9000
spring:
  application:
    name: platform-provider-user
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
logging:
  config: classpath:logback.xml