spring:
  application:
    name: platform-eureka
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  config: classpath:logback.xml
